### ISSUE TITLE
Creating a new query with invalid CQP query string causes server error and invalid data

### ISSUE THREAD

**Issue by flomei** [ausgerechnet/cwb-cads#2]
Adding a new Query using `POST /queries/` with an certain values for `cqp_query`  can cause a 500 error response. I assume the culprit is an invalid CQP query that cannot be executed.
`GET /queries/` will then return an additional entry. This new entry however is malformed, because `cqp_nqr_matches` will be `null` which does not adhere to our OpenAPI spec.

### Expected behavior

Server responds with a 404.
Ideally the response also contains a meaningful error message about what the issue with the query is.

### Steps to reproduce

1. Make a POST request to `/queries/` with a nonsense value for `cqp_query`.
   e.g.:
  ```bash
curl -X 'POST' \
  'https://corpora.linguistik.uni-erlangen.de/cwb-cads-dev/query/?execute=true' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer AUTH_TOKEN_GOES_HERE \
  -H 'Content-Type: application/json' \
  -d '{
  "corpus_id": 1,
  "cqp_query": "!!I_Am_Invalid!!",
  "match_strategy": "longest",
  "s": "s"
}'
```
2. Inspect the response from `GET /queries/` and check for `cqp_nqr_matches: null`

**Comment by ausgerechnet** [comment]
this is not too complicated and reasonable. I'll push a fix this afternoon.
